# Generated by Django 5.0.1 on 2024-03-10 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_selection', '0002_useranswers_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswers',
            name='average_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
