# Generated by Django 5.0.2 on 2024-03-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_selection', '0003_alter_githubusercontribution_daily_commits_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='answer_downvotes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='answer_upvotes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='question_downvotes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='question_upvotes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='total_answers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionanswer',
            name='total_questions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
