# Generated by Django 5.0.1 on 2024-03-07 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_selection', '0003_alter_githubusercontribution_daily_commits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer1', models.CharField(max_length=100)),
                ('answer2', models.CharField(max_length=100)),
                ('answer3', models.CharField(max_length=100)),
                ('score_answer1', models.IntegerField()),
                ('score_answer2', models.IntegerField()),
                ('score_answer3', models.IntegerField()),
                ('total_score', models.IntegerField()),
                ('status', models.CharField(default='failed', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate_selection.user')),
            ],
        ),
    ]
