# Generated by Django 5.0.1 on 2024-03-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_selection', '0004_useranswers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswers',
            name='answer1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='answer2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='answer3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='score_answer1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='score_answer2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='score_answer3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='total_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
