# Generated by Django 5.0.1 on 2024-03-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_selection', '0005_alter_useranswers_answer1_alter_useranswers_answer2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswers',
            name='score_answer1',
        ),
        migrations.RemoveField(
            model_name='useranswers',
            name='score_answer2',
        ),
        migrations.RemoveField(
            model_name='useranswers',
            name='score_answer3',
        ),
        migrations.RemoveField(
            model_name='useranswers',
            name='total_score',
        ),
        migrations.AlterField(
            model_name='useranswers',
            name='status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
